package com.tva.missminutes.ai

import android.content.Context
import android.util.Log
import io.livekit.android.LiveKit
import io.livekit.android.LiveKitOverrides
import io.livekit.android.room.Room
import io.livekit.android.room.participant.LocalParticipant
import io.livekit.android.room.track.CameraPosition
import io.livekit.android.room.track.LocalAudioTrack
import io.livekit.android.room.track.LocalVideoTrack
import io.livekit.android.room.track.Track
import io.livekit.android.events.RoomEvent
import io.livekit.android.util.flow
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.filterIsInstance
import kotlinx.coroutines.flow.map
import kotlinx.coroutines.launch

private const val TAG = "JarvisLiveKit"

/** LiveKit connection states */
sealed class LiveKitState {
    object Disconnected : LiveKitState()
    data class Connecting(val serverUrl: String) : LiveKitState()
    object Connected : LiveKitState()
    object AgentSpeaking : LiveKitState()
    data class Error(val message: String) : LiveKitState()
}

/**
 * JarvisLiveKitManager — manages the LiveKit WebRTC room connection for J.A.R.V.I.S.
 *
 * Handles:
 *  - Connecting to the local LiveKit server (running on your PC)
 *  - Publishing microphone audio to the room (J.A.R.V.I.S. listens)
 *  - Publishing camera video to the room (J.A.R.V.I.S. sees)
 *  - Receiving agent TTS audio back (J.A.R.V.I.S. speaks)
 *  - Exposing connection state to the UI
 *
 * Default room URL: ws://192.168.x.x:7880 (your PC's local IP)
 * Token:           devkey:devsecret in dev mode (LiveKit --dev flag)
 */
class JarvisLiveKitManager(private val context: Context) {

    // ── LiveKit Room ──────────────────────────────────────────────────────────
    private var room: Room? = null
    private var managerScope = CoroutineScope(Dispatchers.Main + Job())

    // ── State ─────────────────────────────────────────────────────────────────
    private val _state = MutableStateFlow<LiveKitState>(LiveKitState.Disconnected)
    val state: StateFlow<LiveKitState> = _state.asStateFlow()

    private val _cameraEnabled = MutableStateFlow(false)
    val cameraEnabled: StateFlow<Boolean> = _cameraEnabled.asStateFlow()

    private val _micEnabled = MutableStateFlow(false)
    val micEnabled: StateFlow<Boolean> = _micEnabled.asStateFlow()

    // Agent amplitude (for orb animation when JARVIS speaks)
    private val _agentAmplitude = MutableStateFlow(0f)
    val agentAmplitude: StateFlow<Float> = _agentAmplitude.asStateFlow()

    // ── Tracks ─────────────────────────────────────────────────────────────────
    private var localVideoTrack: LocalVideoTrack? = null

    val isConnected: Boolean
        get() = _state.value is LiveKitState.Connected || _state.value is LiveKitState.AgentSpeaking

    // ─────────────────────────────────────────────────────────────────────────
    // Connection
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Connect to J.A.R.V.I.S. agent room.
     *
     * @param serverUrl LiveKit server WebSocket URL, e.g. "ws://192.168.1.100:7880"
     * @param token     LiveKit access token (generated by generateDevToken)
     */
    suspend fun connect(serverUrl: String, token: String) {
        if (isConnected) {
            Log.w(TAG, "Already connected — ignoring connect request")
            return
        }

        try {
            _state.value = LiveKitState.Connecting(serverUrl)
            Log.i(TAG, "Connecting to J.A.R.V.I.S. at $serverUrl")

            val liveKitRoom = LiveKit.create(context)
            room = liveKitRoom

            // Listen for room events
            observeRoomEvents(liveKitRoom)

            liveKitRoom.connect(serverUrl, token)

            // Enable microphone immediately after connecting
            liveKitRoom.localParticipant.setMicrophoneEnabled(true)
            _micEnabled.value = true

            _state.value = LiveKitState.Connected
            Log.i(TAG, "✅ J.A.R.V.I.S. connected — all systems operational")

        } catch (e: Exception) {
            Log.e(TAG, "Connection failed", e)
            _state.value = LiveKitState.Error("Connection failed: ${e.message?.take(60)}")
            room = null
        }
    }

    /** Disconnect cleanly from the room */
    fun disconnect() {
        managerScope.launch {
            try {
                stopCamera()
                room?.disconnect()
                Log.i(TAG, "J.A.R.V.I.S. disconnected")
            } catch (e: Exception) {
                Log.w(TAG, "Disconnect warning: ${e.message}")
            } finally {
                room = null
                _state.value = LiveKitState.Disconnected
                _micEnabled.value = false
                _cameraEnabled.value = false
            }
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Camera
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Toggle camera on/off. When on, video is streamed to J.A.R.V.I.S. agent.
     * @param useFrontCamera true = selfie camera, false = rear camera
     */
    suspend fun toggleCamera(useFrontCamera: Boolean = true) {
        val currentRoom = room ?: return

        if (_cameraEnabled.value) {
            stopCamera()
        } else {
            startCamera(currentRoom, useFrontCamera)
        }
    }

    private suspend fun startCamera(room: Room, useFrontCamera: Boolean) {
        try {
            val position = if (useFrontCamera) CameraPosition.FRONT else CameraPosition.BACK
            room.localParticipant.setCameraEnabled(true, position)
            _cameraEnabled.value = true
            Log.i(TAG, "Camera enabled (${if (useFrontCamera) "front" else "rear"})")
        } catch (e: Exception) {
            Log.e(TAG, "Camera start failed", e)
            _cameraEnabled.value = false
        }
    }

    private fun stopCamera() {
        try {
            managerScope.launch {
                room?.localParticipant?.setCameraEnabled(false)
            }
            localVideoTrack?.stop()
            localVideoTrack = null
            _cameraEnabled.value = false
            Log.i(TAG, "Camera disabled")
        } catch (e: Exception) {
            Log.w(TAG, "Camera stop warning: ${e.message}")
        }
    }

    /** Switch between front and rear camera */
    suspend fun flipCamera() {
        room?.localParticipant?.let { participant ->
            val videoTrack = participant.getTrackPublication(Track.Source.CAMERA)
            if (videoTrack != null) {
                stopCamera()
                startCamera(room!!, useFrontCamera = !_cameraEnabled.value)
            }
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Mic
    // ─────────────────────────────────────────────────────────────────────────

    fun setMicEnabled(enabled: Boolean) {
        managerScope.launch {
            room?.localParticipant?.setMicrophoneEnabled(enabled)
            _micEnabled.value = enabled
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Room event observation
    // ─────────────────────────────────────────────────────────────────────────

    private fun observeRoomEvents(liveKitRoom: Room) {
        managerScope.launch {
            liveKitRoom.events.collect { event ->
                when (event) {
                    is RoomEvent.Disconnected -> {
                        Log.w(TAG, "Room disconnected: ${event.reason}")
                        _state.value = LiveKitState.Disconnected
                        _micEnabled.value = false
                        _cameraEnabled.value = false
                    }
                    is RoomEvent.ParticipantConnected -> {
                        Log.i(TAG, "Participant joined: ${event.participant.identity}")
                        // Agent has joined — we're fully live
                        if (_state.value is LiveKitState.Connected) {
                            _state.value = LiveKitState.Connected
                        }
                    }
                    is RoomEvent.TrackSubscribed -> {
                        Log.i(TAG, "Track subscribed: ${event.track.kind} from ${event.participant.identity}")
                    }
                    is RoomEvent.ConnectionQualityChanged -> {
                        Log.d(TAG, "Connection quality: ${event.quality}")
                    }
                    else -> { /* other events */ }
                }
            }
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Token Generation (dev mode — LiveKit --dev flag)
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Generate a dev-mode LiveKit access token using the livekit-api library.
     *
     * The LiveKit server must be started with --dev (which sets key=devkey, secret=devsecret).
     * For production, generate tokens server-side.
     *
     * @param apiKey    LiveKit API key (default: "devkey" for --dev servers)
     * @param apiSecret LiveKit API secret (default: "devsecret" for --dev servers)
     * @param roomName  Room to join (default: "jarvis-room")
     * @param identity  Participant identity (default: "android-user")
     */
    fun generateDevToken(
        apiKey: String = "devkey",
        apiSecret: String = "devsecret",
        roomName: String = "jarvis-room",
        identity: String = "android-user"
    ): String {
        // We use a hand-crafted JWT for dev mode since importing livekit-api
        // server SDK adds overhead. This is ONLY for dev/--dev servers.
        // Format: header.payload.signature (simplified for devkey)
        return buildDevJwt(apiKey, apiSecret, roomName, identity)
    }

    private fun buildDevJwt(
        apiKey: String,
        apiSecret: String,
        roomName: String,
        identity: String
    ): String {
        // JWT for LiveKit dev mode — expiry 24h from now
        val now = System.currentTimeMillis() / 1000
        val exp = now + (24 * 3600)

        val header = android.util.Base64.encodeToString(
            """{"alg":"HS256","typ":"JWT"}""".toByteArray(),
            android.util.Base64.URL_SAFE or android.util.Base64.NO_PADDING or android.util.Base64.NO_WRAP
        )

        val payload = android.util.Base64.encodeToString(
            """{"iss":"$apiKey","sub":"$identity","iat":$now,"exp":$exp,"video":{"room":"$roomName","roomJoin":true,"canPublish":true,"canSubscribe":true,"canPublishData":true}}""".toByteArray(),
            android.util.Base64.URL_SAFE or android.util.Base64.NO_PADDING or android.util.Base64.NO_WRAP
        )

        val message = "$header.$payload"
        val key = javax.crypto.spec.SecretKeySpec(apiSecret.toByteArray(), "HmacSHA256")
        val mac = javax.crypto.Mac.getInstance("HmacSHA256")
        mac.init(key)
        val sig = android.util.Base64.encodeToString(
            mac.doFinal(message.toByteArray()),
            android.util.Base64.URL_SAFE or android.util.Base64.NO_PADDING or android.util.Base64.NO_WRAP
        )

        return "$message.$sig"
    }

    fun release() {
        disconnect()
        managerScope.launch {
            room?.release()
        }
    }
}
